### ISSUE TITLE
Section: Spammer

### ISSUE THREAD

**Issue by borz-txt** [Muffinmaker2/Augustus-Wiki#6]
### What is the Correction?

The last mode is “Custom”. 
You can set a custom message to send with the command .spammer [ your message ] 
And with the delays you can set the time between the messages.

**Comment by Muffinmaker2** [comment]
Would this be correct?
![grafik](https://github.com/user-attachments/assets/bb35ea74-f826-4f87-9acf-46af6c14a0d3)

**Comment by borz-txt** [comment]
“Spammer can be configured with the mode “Custom”. With that mode you can spam your custom message by typing  _.spammer [your message]_. 

this would be more understandable

**Comment by Muffinmaker2** [comment]
Will add one of those you suggested when im home :D

**Comment by borz-txt** [comment]
Thanks No problem <3

**Comment by Muffinmaker2** [comment]
Has beed added and will be released with the next PR or Merge Thank you <3
